### ISSUE TITLE
Local file paths in requirements.txt

### ISSUE THREAD

**Issue by abukharin3** [parshinsh/rl_code#3]
Hi, I am trying to install the requirements from requirements.txt with pip install -r requirements.txt, but this results in an error saying the file "/home/ktietz/src/ci/alabaster_1611921520/work" does not exist. I was wondering how I can set up an environment to run your codebase? Thanks!

**Comment by azadsalam** [comment]
+1

I also faced the same problem!

**Comment by peppa-xyz** [comment]
Have you solved this problem?

**Comment by parshinsh** [comment]
@abukharin3 @peppa-nwpu The `requirements.txt` file is updated.

**Comment by parshinsh** [comment]
#5

**Comment by Symbolk** [comment]
> @abukharin3 @peppa-nwpu The `requirements.txt` file is updated.

Is all the dependencies neccessary for this project? Since requirements.txt seldom reaches 250+, how did you export it? Installing all of them and their dependencies is really a nightmare.
