### ISSUE TITLE
A set of tests in which the code accomplishes the task

### ISSUE THREAD

**Issue by lbl159357** [parshinsh/rl_code#4]
Hello, can you publish the test set of code completion tasks in the repository? Thank you very much

**Comment by parshinsh** [comment]
@lbl159357 For the code completion task, we assess compilation success rate. The scripts and test cases for compilation evaluation is provided in `terminal_compiler.py` and `test.py` located in the `./compiler` folder [here](https://github.com/reddy-lab-code-research/PPOCoder/blob/main/compiler/). 
Please refer to #7 for more information.
