### ISSUE TITLE
About Running on tasks other than Program Translation

### ISSUE THREAD

**Issue by lhaausing** [parshinsh/rl_code#8]
Hi,

I have looked at the code base. Seems like it only shows examples on how to run program translation code. I'm wondering how should we change the arguments if we want to run on program synthesis task, in which the source language is english text.

Best regards.

**Comment by Symbolk** [comment]
+1. This a nice work with clear code structure! 

Howeve, from the code and doc, it seems to be solely for Translation task. How can we refactor the code to Program Synthesis/Generation task and replace CodeT5 with GPT-like models? @parshinsh

**Comment by XiaoXiaoYi123** [comment]
The value of reward_coef doesn't seem to be defined in the code

**Comment by parshinsh** [comment]
Thanks for your interest! 

@lhaausing @Symbolk To run the framework for other tasks, you just need to place your chosen dataset (e.g., APPS in case of program synthesis) in the `data` folder and adjust the hyperparameters as specified in [Appendix A](https://openreview.net/pdf?id=0XBuaxqEcG) Implementation Details. For how to obtain and preprocess APPS, refer to #6 .

@Symbolk keep in mind that PPOCoder updates models using code-specific feedback, so the weights of your pre-trained model should be accessible. You can modify `HeadWithValueModel` [here](https://github.com/reddy-lab-code-research/PPOCoder/blob/main/model.py) to point to your preferred pre-trained model's path and modules.

**Comment by parshinsh** [comment]
@XiaoXiaoYi123 Thanks for bringing this to our attention! It is fixed now.
