### ISSUE TITLE
When calculating value function loss, it seems that the value function has not been updated, and the new value function is equal to the old value function. Is this situation reasonable

### ISSUE THREAD

**Issue by WUHU-G** [parshinsh/rl_code#9]
![20230703230947](https://github.com/reddy-lab-code-research/PPOCoder/assets/50363920/d0f3b2c1-26cd-46dd-8388-7ea31f0e9160)

**Comment by WUHU-G** [comment]
vpred == values??

**Comment by parshinsh** [comment]
@FastBCSD  `vpred` and `values` actually represent different concepts. In this implementation, `values` refers to the estimated values from the old policy, while `vpred` refers to the value estimated by the new policy. The value loss is indeed calculated as the squared error term between `returns` and the newly estimated values `vpred`. However, `returns` itself is also derived from old values and the newly estimated advantage. For further details, you can refer to [Section 3.3](https://openreview.net/pdf?id=0XBuaxqEcG) of the paper.
